fix: address crash caused by lessonManager non-initialized issue
- crash log:
kotlin.UninitializedPropertyAccessException: lateinit property lessonManager has not been initialized